version: '3.1'

services:

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
        - '5432:5432'
    volumes: 
        - './data:/var/lib/postgresql/data'
        # - './postgres_scripts:/docker-entrypoint-initdb.d'
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '9080:8080'